// Code generated by cli-gen. DO NOT EDIT.
package sub

import (
	"github.com/nokamoto/2pf23/internal/cli/runtime"
	"github.com/spf13/cobra"
)

func NewRoot(rt runtime.Runtime) *cobra.Command {
	cmd := &cobra.Command{
		Use:          "sub",
		Short:        "short",
		Long:         `long`,
	}
	return cmd
}
