// Code generated by cli-gen. DO NOT EDIT.
package cligen

import (
	"github.com/nokamoto/2pf23/internal/cli/runtime"
	"github.com/spf13/cobra"
)

func NewRoot(rt runtime.Runtime) *cobra.Command {
	cmd := &cobra.Command{
		Use:          "testdata",
		Short:        "short",
		Long:         `long`,
	}
	cmd.AddCommand(newCreate(rt))
	cmd.AddCommand(sub.NewRoot(rt))
	return cmd
}
