// Code generated by cli-gen. DO NOT EDIT.
package cligen

import (
	"github.com/spf13/cobra"
)

func NewRoot() *cobra.Command {
	cmd := &cobra.Command{
		Use:          "testdata",
		Short:        "short",
		Long:         `long`,
	}

	cmd.AddCommand(newCreate())

	return cmd
}
