name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: make build
        env:
          KO_DOCKER_REPO: ko.local
      - name: setup-ko
        run: |
          # NB: username doesn't seem to matter.
          echo "${{ github.token }}" | ko login ghcr.io --username "dummy" --password-stdin
      - run: make build
