name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - name: make build (ko.local)
        run: make build
        env:
          KO_DOCKER_REPO: ko.local
      - name: ko login
        run: |
          # NB: username doesn't seem to matter.
          echo "${{ github.token }}" | ko login ghcr.io --username "dummy" --password-stdin
      - name: make build (ghcr.io)
        run: make build
