name: Go

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'web/**'
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'web/**'
      - '**.md'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-${{ hashFiles('**/Makefile') }}
      - run: make test
      - run: git diff --exit-code
      - uses: codecov/codecov-action@v3
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          cache: false
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - name: make build (ko.local)
        run: make build
        env:
          KO_DOCKER_REPO: ko.local
