name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - uses: actions/cache@v3
        with:
           path: ~/go/bin
           key: ${{ runner.os }}-${{ hashFiles('**/build/.tools') }}
      - run: make all
      - run: git diff --exit-code
      - uses: codecov/codecov-action@v3
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - name: make build (ko.local)
        run: make build
        env:
          KO_DOCKER_REPO: ko.local
