name: TypeScript

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '**.md'
      - 'testdata/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '**.md'
      - 'testdata/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
        working-directory: web/2pf23console
      - run: npm run test
        working-directory: web/2pf23console
      - run: git diff --exit-code
      - uses: codecov/codecov-action@v3
        working-directory: web/2pf23console
