// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: api/inhouse/v1/cligen.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Flag represents command line flag.
//
// ```
// var displayName string
// cmd.Flags().StringVar(&displayName, "display-name", "default value", "usage string")
// ```
type Flag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the variable name.
	// e.g. displayName
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// display_name is the display name of the flag.
	// e.g. display-name
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// value is the default value of the flag.
	// e.g. default value
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// usage is the usage string of the flag.
	// e.g. usage string
	Usage string `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *Flag) Reset() {
	*x = Flag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_inhouse_v1_cligen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_api_inhouse_v1_cligen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_api_inhouse_v1_cligen_proto_rawDescGZIP(), []int{0}
}

func (x *Flag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flag) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Flag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Flag) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

// RequestMessageField represents golang struct field value.
//
// ```
// Displayname: displayName
// ```
type RequestMessageField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the field name.
	// e.g. DisplayName
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// value is the field value.
	// e.g. displayName
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RequestMessageField) Reset() {
	*x = RequestMessageField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_inhouse_v1_cligen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMessageField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessageField) ProtoMessage() {}

func (x *RequestMessageField) ProtoReflect() protoreflect.Message {
	mi := &file_api_inhouse_v1_cligen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessageField.ProtoReflect.Descriptor instead.
func (*RequestMessageField) Descriptor() ([]byte, []int) {
	return file_api_inhouse_v1_cligen_proto_rawDescGZIP(), []int{1}
}

func (x *RequestMessageField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestMessageField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// RequestMessage represents golang struct.
//
// ```
//
//	&v1alpha.ClusterCreateRequest {
//	  Cluster: &v1alpha.Cluster {
//	    DisplayName: displayName,
//	  }
//	}
//
// ```
type RequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the field set by this message.
	// e.g. Cluster
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type is the type of the field.
	// e.g. v1alpha.Cluster
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// fields is the list of non message fields.
	Fields []*RequestMessageField `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// children is the list of message fields.
	Children []*RequestMessage `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_inhouse_v1_cligen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_inhouse_v1_cligen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_api_inhouse_v1_cligen_proto_rawDescGZIP(), []int{2}
}

func (x *RequestMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RequestMessage) GetFields() []*RequestMessageField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *RequestMessage) GetChildren() []*RequestMessage {
	if x != nil {
		return x.Children
	}
	return nil
}

// ResponseMessage represents golang struct.
//
// ```
// var cluster *v1alpha.ListClusterResponse
// cluster.Clusters = append(cluster.Clusters, cluster.Clusters...)
// ```
type ResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// type is the type of the response.
	// e.g. v1alpha.ListClusterResponse
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// list_field is the field name of the resource list.
	// e.g. Clusters
	ListField string `protobuf:"bytes,2,opt,name=list_field,json=listField,proto3" json:"list_field,omitempty"`
}

func (x *ResponseMessage) Reset() {
	*x = ResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_inhouse_v1_cligen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMessage) ProtoMessage() {}

func (x *ResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_inhouse_v1_cligen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMessage.ProtoReflect.Descriptor instead.
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return file_api_inhouse_v1_cligen_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResponseMessage) GetListField() string {
	if x != nil {
		return x.ListField
	}
	return ""
}

// Command represents golang code to call a single gRPC method.
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// api is the name of the gRPC API.
	// e.g. ke
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// api_version is the version of the gRPC API.
	// e.g. v1alpha
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// api_import_path is the import path of the gRPC API.
	// e.g. github.com/nokamoto/2pf23/pkg/api/ke/v1alpha
	ApiImportPath *ImportPath `protobuf:"bytes,3,opt,name=api_import_path,json=apiImportPath,proto3" json:"api_import_path,omitempty"`
	// package is the name of the generated code package.
	// e.g. cluster
	Package string `protobuf:"bytes,4,opt,name=package,proto3" json:"package,omitempty"`
	// use is the name of the command.
	// e.g. create
	Use string `protobuf:"bytes,5,opt,name=use,proto3" json:"use,omitempty"`
	// short is the short description of the command.
	Short string `protobuf:"bytes,6,opt,name=short,proto3" json:"short,omitempty"`
	// long is the long description of the command.
	Long string `protobuf:"bytes,7,opt,name=long,proto3" json:"long,omitempty"`
	// method is the name of the gRPC method.
	// e.g. CreateCluster
	Method string `protobuf:"bytes,8,opt,name=method,proto3" json:"method,omitempty"`
	// method_type is the type of the gRPC method.
	MethodType MethodType `protobuf:"varint,9,opt,name=method_type,json=methodType,proto3,enum=api.inhouse.v1.MethodType" json:"method_type,omitempty"`
	// request is the request message passed to the gRPC method at runtime.
	Request *RequestMessage `protobuf:"bytes,11,opt,name=request,proto3" json:"request,omitempty"`
	// response is the response message returned from the gRPC method at runtime.
	Response *ResponseMessage `protobuf:"bytes,12,opt,name=response,proto3" json:"response,omitempty"`
	// string_flags is the list of string flags of the command.
	StringFlags []*Flag `protobuf:"bytes,13,rep,name=string_flags,json=stringFlags,proto3" json:"string_flags,omitempty"`
	// int32_flags is the list of number flags of the command.
	Int32Flags []*Flag `protobuf:"bytes,14,rep,name=int32_flags,json=int32Flags,proto3" json:"int32_flags,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_inhouse_v1_cligen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_inhouse_v1_cligen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_inhouse_v1_cligen_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *Command) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Command) GetApiImportPath() *ImportPath {
	if x != nil {
		return x.ApiImportPath
	}
	return nil
}

func (x *Command) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Command) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *Command) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *Command) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *Command) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Command) GetMethodType() MethodType {
	if x != nil {
		return x.MethodType
	}
	return MethodType_METHOD_TYPE_UNSPECIFIED
}

func (x *Command) GetRequest() *RequestMessage {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Command) GetResponse() *ResponseMessage {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Command) GetStringFlags() []*Flag {
	if x != nil {
		return x.StringFlags
	}
	return nil
}

func (x *Command) GetInt32Flags() []*Flag {
	if x != nil {
		return x.Int32Flags
	}
	return nil
}

// Package represents golang codes hierarchy and root command.
//
// The root command is the entry point of the CLI.
// The hierarchy of the commands is represented by sub_commands and sub_packages.
//
// {root-directory}
// ├── ke
// │   ├── root.go
// │   └── v1alpha
// │       ├── cluster
// │       │   ├── createcluster.go
// │       │   └── root.go
// │       └── root.go
// └── root.go
type Package struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// package is the name of the generated code package.
	// e.g. cluster
	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	// use is the name of the root command.
	Use string `protobuf:"bytes,3,opt,name=use,proto3" json:"use,omitempty"`
	// short is the short description of the root command.
	Short string `protobuf:"bytes,4,opt,name=short,proto3" json:"short,omitempty"`
	// long is the long description of the root command.
	Long string `protobuf:"bytes,5,opt,name=long,proto3" json:"long,omitempty"`
	// sub_commands is the list of sub commands.
	// The root command adds sub commands to the CLI.
	SubCommands []*Command `protobuf:"bytes,6,rep,name=sub_commands,json=subCommands,proto3" json:"sub_commands,omitempty"`
	// sub_packages is the list of sub packages.
	// The root command adds root commands of sub packages to the CLI.
	SubPackages []*Package `protobuf:"bytes,7,rep,name=sub_packages,json=subPackages,proto3" json:"sub_packages,omitempty"`
}

func (x *Package) Reset() {
	*x = Package{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_inhouse_v1_cligen_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_api_inhouse_v1_cligen_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_api_inhouse_v1_cligen_proto_rawDescGZIP(), []int{5}
}

func (x *Package) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Package) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *Package) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *Package) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *Package) GetSubCommands() []*Command {
	if x != nil {
		return x.SubCommands
	}
	return nil
}

func (x *Package) GetSubPackages() []*Package {
	if x != nil {
		return x.SubPackages
	}
	return nil
}

var File_api_inhouse_v1_cligen_proto protoreflect.FileDescriptor

var file_api_inhouse_v1_cligen_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61,
	0x70, 0x69, 0x2e, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x18, 0x61,
	0x70, 0x69, 0x2f, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x3f, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0xb1, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3b,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x3a, 0x0a, 0x08, 0x63,
	0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x63,
	0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x22, 0x44, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x92, 0x04,
	0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12, 0x1f, 0x0a, 0x0b, 0x61,
	0x70, 0x69, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x0f,
	0x61, 0x70, 0x69, 0x5f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x61, 0x74,
	0x68, 0x52, 0x0d, 0x61, 0x70, 0x69, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x73,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x3b,
	0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69,
	0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x0b,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x35, 0x0a, 0x0b, 0x69,
	0x6e, 0x74, 0x33, 0x32, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x46, 0x6c, 0x61,
	0x67, 0x73, 0x22, 0xd7, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x73, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6c, 0x6f, 0x6e, 0x67, 0x12, 0x3a, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x12, 0x3a, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52,
	0x0b, 0x73, 0x75, 0x62, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x42, 0x2e, 0x5a, 0x2c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x6b, 0x61, 0x6d,
	0x6f, 0x74, 0x6f, 0x2f, 0x32, 0x70, 0x66, 0x32, 0x33, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_inhouse_v1_cligen_proto_rawDescOnce sync.Once
	file_api_inhouse_v1_cligen_proto_rawDescData = file_api_inhouse_v1_cligen_proto_rawDesc
)

func file_api_inhouse_v1_cligen_proto_rawDescGZIP() []byte {
	file_api_inhouse_v1_cligen_proto_rawDescOnce.Do(func() {
		file_api_inhouse_v1_cligen_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_inhouse_v1_cligen_proto_rawDescData)
	})
	return file_api_inhouse_v1_cligen_proto_rawDescData
}

var file_api_inhouse_v1_cligen_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_inhouse_v1_cligen_proto_goTypes = []interface{}{
	(*Flag)(nil),                // 0: api.inhouse.v1.Flag
	(*RequestMessageField)(nil), // 1: api.inhouse.v1.RequestMessageField
	(*RequestMessage)(nil),      // 2: api.inhouse.v1.RequestMessage
	(*ResponseMessage)(nil),     // 3: api.inhouse.v1.ResponseMessage
	(*Command)(nil),             // 4: api.inhouse.v1.Command
	(*Package)(nil),             // 5: api.inhouse.v1.Package
	(*ImportPath)(nil),          // 6: api.inhouse.v1.ImportPath
	(MethodType)(0),             // 7: api.inhouse.v1.MethodType
}
var file_api_inhouse_v1_cligen_proto_depIdxs = []int32{
	1,  // 0: api.inhouse.v1.RequestMessage.fields:type_name -> api.inhouse.v1.RequestMessageField
	2,  // 1: api.inhouse.v1.RequestMessage.children:type_name -> api.inhouse.v1.RequestMessage
	6,  // 2: api.inhouse.v1.Command.api_import_path:type_name -> api.inhouse.v1.ImportPath
	7,  // 3: api.inhouse.v1.Command.method_type:type_name -> api.inhouse.v1.MethodType
	2,  // 4: api.inhouse.v1.Command.request:type_name -> api.inhouse.v1.RequestMessage
	3,  // 5: api.inhouse.v1.Command.response:type_name -> api.inhouse.v1.ResponseMessage
	0,  // 6: api.inhouse.v1.Command.string_flags:type_name -> api.inhouse.v1.Flag
	0,  // 7: api.inhouse.v1.Command.int32_flags:type_name -> api.inhouse.v1.Flag
	4,  // 8: api.inhouse.v1.Package.sub_commands:type_name -> api.inhouse.v1.Command
	5,  // 9: api.inhouse.v1.Package.sub_packages:type_name -> api.inhouse.v1.Package
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_inhouse_v1_cligen_proto_init() }
func file_api_inhouse_v1_cligen_proto_init() {
	if File_api_inhouse_v1_cligen_proto != nil {
		return
	}
	file_api_inhouse_v1_gen_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_inhouse_v1_cligen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Flag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_inhouse_v1_cligen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMessageField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_inhouse_v1_cligen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_inhouse_v1_cligen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_inhouse_v1_cligen_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_inhouse_v1_cligen_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Package); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_inhouse_v1_cligen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_inhouse_v1_cligen_proto_goTypes,
		DependencyIndexes: file_api_inhouse_v1_cligen_proto_depIdxs,
		MessageInfos:      file_api_inhouse_v1_cligen_proto_msgTypes,
	}.Build()
	File_api_inhouse_v1_cligen_proto = out.File
	file_api_inhouse_v1_cligen_proto_rawDesc = nil
	file_api_inhouse_v1_cligen_proto_goTypes = nil
	file_api_inhouse_v1_cligen_proto_depIdxs = nil
}
