// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: api/inhouse/v1/servergen.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service represents golang code to receive gRPC requests.
type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// package is the name of the package.
	// e.g. ke
	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	// api_import_path is the import path of the gRPC API.
	// e.g. github.com/nokamoto/2pf23/pkg/api/ke/v1alpha
	ApiImportPath *ImportPath `protobuf:"bytes,2,opt,name=api_import_path,json=apiImportPath,proto3" json:"api_import_path,omitempty"`
	// unimplemented_server is the name of the unimplemented server.
	// e.g. v1alpha.UnimplementedKeServer
	UnimplementedServer string `protobuf:"bytes,3,opt,name=unimplemented_server,json=unimplementedServer,proto3" json:"unimplemented_server,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_inhouse_v1_servergen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_inhouse_v1_servergen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_api_inhouse_v1_servergen_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Service) GetApiImportPath() *ImportPath {
	if x != nil {
		return x.ApiImportPath
	}
	return nil
}

func (x *Service) GetUnimplementedServer() string {
	if x != nil {
		return x.UnimplementedServer
	}
	return ""
}

var File_api_inhouse_v1_servergen_proto protoreflect.FileDescriptor

var file_api_inhouse_v1_servergen_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31,
	0x1a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a, 0x01, 0x0a, 0x07, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x12, 0x42, 0x0a, 0x0f, 0x61, 0x70, 0x69, 0x5f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x50, 0x61, 0x74, 0x68, 0x52, 0x0d, 0x61, 0x70, 0x69, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x31, 0x0a, 0x14, 0x75, 0x6e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x13, 0x75, 0x6e, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x6b, 0x61, 0x6d, 0x6f, 0x74, 0x6f, 0x2f, 0x32,
	0x70, 0x66, 0x32, 0x33, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_inhouse_v1_servergen_proto_rawDescOnce sync.Once
	file_api_inhouse_v1_servergen_proto_rawDescData = file_api_inhouse_v1_servergen_proto_rawDesc
)

func file_api_inhouse_v1_servergen_proto_rawDescGZIP() []byte {
	file_api_inhouse_v1_servergen_proto_rawDescOnce.Do(func() {
		file_api_inhouse_v1_servergen_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_inhouse_v1_servergen_proto_rawDescData)
	})
	return file_api_inhouse_v1_servergen_proto_rawDescData
}

var file_api_inhouse_v1_servergen_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_inhouse_v1_servergen_proto_goTypes = []interface{}{
	(*Service)(nil),    // 0: api.inhouse.v1.Service
	(*ImportPath)(nil), // 1: api.inhouse.v1.ImportPath
}
var file_api_inhouse_v1_servergen_proto_depIdxs = []int32{
	1, // 0: api.inhouse.v1.Service.api_import_path:type_name -> api.inhouse.v1.ImportPath
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_inhouse_v1_servergen_proto_init() }
func file_api_inhouse_v1_servergen_proto_init() {
	if File_api_inhouse_v1_servergen_proto != nil {
		return
	}
	file_api_inhouse_v1_gen_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_inhouse_v1_servergen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_inhouse_v1_servergen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_inhouse_v1_servergen_proto_goTypes,
		DependencyIndexes: file_api_inhouse_v1_servergen_proto_depIdxs,
		MessageInfos:      file_api_inhouse_v1_servergen_proto_msgTypes,
	}.Build()
	File_api_inhouse_v1_servergen_proto = out.File
	file_api_inhouse_v1_servergen_proto_rawDesc = nil
	file_api_inhouse_v1_servergen_proto_goTypes = nil
	file_api_inhouse_v1_servergen_proto_depIdxs = nil
}
