// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: api/inhouse/v1/servergen.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Call represents a gRPC call.
type Call struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the name of the call.
	// e.g. CreateCluster
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// method_type is the type of the method.
	MethodType MethodType `protobuf:"varint,2,opt,name=method_type,json=methodType,proto3,enum=api.inhouse.v1.MethodType" json:"method_type,omitempty"`
	// request_type is the type of the gRPC request.
	// e.g. v1alpha.CreateClusterRequest
	RequestType string `protobuf:"bytes,3,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
	// response_type is the type of the gRPC response.
	// e.g. v1alpha.Cluster
	ResponseType string `protobuf:"bytes,4,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	// resource_type is the type of the resource.
	// e.g. v1alpha.Cluster
	ResourceType string `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// get_resource_method is the name of the method to get the resource from the request.
	// e.g. GetCluster
	GetResourceMethod string `protobuf:"bytes,6,opt,name=get_resource_method,json=getResourceMethod,proto3" json:"get_resource_method,omitempty"`
	// list_field is the name of the field to set the resource list to the response.
	// e.g. Clusters
	ListField string `protobuf:"bytes,7,opt,name=list_field,json=listField,proto3" json:"list_field,omitempty"`
}

func (x *Call) Reset() {
	*x = Call{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_inhouse_v1_servergen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_api_inhouse_v1_servergen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_api_inhouse_v1_servergen_proto_rawDescGZIP(), []int{0}
}

func (x *Call) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Call) GetMethodType() MethodType {
	if x != nil {
		return x.MethodType
	}
	return MethodType_METHOD_TYPE_UNSPECIFIED
}

func (x *Call) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

func (x *Call) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *Call) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Call) GetGetResourceMethod() string {
	if x != nil {
		return x.GetResourceMethod
	}
	return ""
}

func (x *Call) GetListField() string {
	if x != nil {
		return x.ListField
	}
	return ""
}

// Service represents golang code to receive gRPC requests.
type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the name of the gRPC service.
	// e.g. ke
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// api_version is the version of the gRPC API.
	// e.g. v1alpha
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// api_import_path is the import path of the gRPC API.
	// e.g. github.com/nokamoto/2pf23/pkg/api/ke/v1alpha
	ApiImportPath *ImportPath `protobuf:"bytes,3,opt,name=api_import_path,json=apiImportPath,proto3" json:"api_import_path,omitempty"`
	// calls is the list of gRPC calls.
	Calls []*Call `protobuf:"bytes,4,rep,name=calls,proto3" json:"calls,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_inhouse_v1_servergen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_inhouse_v1_servergen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_api_inhouse_v1_servergen_proto_rawDescGZIP(), []int{1}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Service) GetApiImportPath() *ImportPath {
	if x != nil {
		return x.ApiImportPath
	}
	return nil
}

func (x *Service) GetCalls() []*Call {
	if x != nil {
		return x.Calls
	}
	return nil
}

var File_api_inhouse_v1_servergen_proto protoreflect.FileDescriptor

var file_api_inhouse_v1_servergen_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31,
	0x1a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x02, 0x0a, 0x04, 0x43,
	0x61, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x2e, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x22, 0xae, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x42, 0x0a, 0x0f, 0x61, 0x70, 0x69, 0x5f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x50, 0x61, 0x74, 0x68, 0x52, 0x0d, 0x61, 0x70, 0x69, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2a, 0x0a, 0x05, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x6e, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x05, 0x63, 0x61, 0x6c, 0x6c,
	0x73, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6e, 0x6f, 0x6b, 0x61, 0x6d, 0x6f, 0x74, 0x6f, 0x2f, 0x32, 0x70, 0x66, 0x32, 0x33, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_inhouse_v1_servergen_proto_rawDescOnce sync.Once
	file_api_inhouse_v1_servergen_proto_rawDescData = file_api_inhouse_v1_servergen_proto_rawDesc
)

func file_api_inhouse_v1_servergen_proto_rawDescGZIP() []byte {
	file_api_inhouse_v1_servergen_proto_rawDescOnce.Do(func() {
		file_api_inhouse_v1_servergen_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_inhouse_v1_servergen_proto_rawDescData)
	})
	return file_api_inhouse_v1_servergen_proto_rawDescData
}

var file_api_inhouse_v1_servergen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_inhouse_v1_servergen_proto_goTypes = []interface{}{
	(*Call)(nil),       // 0: api.inhouse.v1.Call
	(*Service)(nil),    // 1: api.inhouse.v1.Service
	(MethodType)(0),    // 2: api.inhouse.v1.MethodType
	(*ImportPath)(nil), // 3: api.inhouse.v1.ImportPath
}
var file_api_inhouse_v1_servergen_proto_depIdxs = []int32{
	2, // 0: api.inhouse.v1.Call.method_type:type_name -> api.inhouse.v1.MethodType
	3, // 1: api.inhouse.v1.Service.api_import_path:type_name -> api.inhouse.v1.ImportPath
	0, // 2: api.inhouse.v1.Service.calls:type_name -> api.inhouse.v1.Call
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_inhouse_v1_servergen_proto_init() }
func file_api_inhouse_v1_servergen_proto_init() {
	if File_api_inhouse_v1_servergen_proto != nil {
		return
	}
	file_api_inhouse_v1_gen_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_inhouse_v1_servergen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Call); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_inhouse_v1_servergen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_inhouse_v1_servergen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_inhouse_v1_servergen_proto_goTypes,
		DependencyIndexes: file_api_inhouse_v1_servergen_proto_depIdxs,
		MessageInfos:      file_api_inhouse_v1_servergen_proto_msgTypes,
	}.Build()
	File_api_inhouse_v1_servergen_proto = out.File
	file_api_inhouse_v1_servergen_proto_rawDesc = nil
	file_api_inhouse_v1_servergen_proto_goTypes = nil
	file_api_inhouse_v1_servergen_proto_depIdxs = nil
}
